// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TwoCents_WebApi.DbContext;

#nullable disable

namespace TwoCents_WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BlogTag", b =>
                {
                    b.Property<string>("BlogsId")
                        .HasColumnType("text");

                    b.Property<int>("TagsId")
                        .HasColumnType("integer");

                    b.HasKey("BlogsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("BlogTag");
                });

            modelBuilder.Entity("TwoCents_WebApi.Entities.Blog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UpvoteCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("TwoCents_WebApi.Entities.RefreshToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("TwoCents_WebApi.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Science",
                            Slug = "science"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Philosophy",
                            Slug = "philosophy"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Math",
                            Slug = "math"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Politics",
                            Slug = "politics"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Technology",
                            Slug = "technology"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Programming",
                            Slug = "programming"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Artificial Intelligence",
                            Slug = "artificial-intelligence"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Machine Learning",
                            Slug = "machine-learning"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Data Science",
                            Slug = "data-science"
                        },
                        new
                        {
                            Id = 10,
                            Name = "History",
                            Slug = "history"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Economics",
                            Slug = "economics"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Psychology",
                            Slug = "psychology"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Sociology",
                            Slug = "sociology"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Health",
                            Slug = "health"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Fitness",
                            Slug = "fitness"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Medicine",
                            Slug = "medicine"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Literature",
                            Slug = "literature"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Art",
                            Slug = "art"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Music",
                            Slug = "music"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Mathematics",
                            Slug = "mathematics"
                        });
                });

            modelBuilder.Entity("TwoCents_WebApi.Entities.Upvote", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("BlogId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "BlogId");

                    b.HasIndex("BlogId");

                    b.ToTable("Upvote");
                });

            modelBuilder.Entity("TwoCents_WebApi.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BlogTag", b =>
                {
                    b.HasOne("TwoCents_WebApi.Entities.Blog", null)
                        .WithMany()
                        .HasForeignKey("BlogsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TwoCents_WebApi.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TwoCents_WebApi.Entities.Blog", b =>
                {
                    b.HasOne("TwoCents_WebApi.Entities.User", "User")
                        .WithMany("Blogs")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TwoCents_WebApi.Entities.RefreshToken", b =>
                {
                    b.HasOne("TwoCents_WebApi.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TwoCents_WebApi.Entities.Upvote", b =>
                {
                    b.HasOne("TwoCents_WebApi.Entities.Blog", "Blog")
                        .WithMany("Upvotes")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TwoCents_WebApi.Entities.User", "User")
                        .WithMany("Upvotes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TwoCents_WebApi.Entities.Blog", b =>
                {
                    b.Navigation("Upvotes");
                });

            modelBuilder.Entity("TwoCents_WebApi.Entities.User", b =>
                {
                    b.Navigation("Blogs");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Upvotes");
                });
#pragma warning restore 612, 618
        }
    }
}
